#!/usr/bin/env bash
# One-time setup for the KDE tray on Linux: installs the systemd --user unit the tray drives,
# then hands over to AKI-Tray.sh. Idempotent — safe to re-run after editing .env.
#
# Usage:
#   ./scripts/install-tray.sh            install the unit and start the tray
#   ./scripts/install-tray.sh --no-tray  install the unit only

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
UNIT_DIR="$HOME/.config/systemd/user"
UNIT_PATH="$UNIT_DIR/aki-mcp.service"
LOG_DIR="$HOME/.aki/mcpsv/logs"
APPS_DIR="$HOME/.local/share/applications"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "No .env in $REPO_ROOT — copy .env.example to .env and fill it in first." >&2
  exit 1
fi

NODE_BIN="$(command -v node || true)"
if [[ -z "$NODE_BIN" ]]; then
  echo "node not found on PATH. Load your nvm/fnm shell first, then re-run." >&2
  exit 1
fi
# nvm/fnm keep node outside /usr/bin, and the unit inherits no PATH of its own.
NODE_DIR="$(dirname "$NODE_BIN")"

read_env() {
  local key="$1" fallback="${2:-}" value=""
  value=$(sed -nE "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*\"?([^\"#]*)\"?.*/\1/p" "$ENV_FILE" | tail -n1)
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "${value:-$fallback}"
}

PANEL_PORT="$(read_env PANEL_PORT 9998)"
PUBLIC_ORIGIN="$(read_env PUBLIC_ORIGIN)"

mkdir -p "$UNIT_DIR" "$LOG_DIR" "$APPS_DIR"

# Qt announces this app ID to the XDG portal. Without a matching desktop entry Plasma logs
# "App info not found" and treats the tray as an unknown app (generic icon, no notification
# settings entry). The file has to be named after the app ID set in tray.py.
cat > "$APPS_DIR/aki-mcp-tray.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=AKI MCP
Comment=AKI MCP server tray icon
Exec=$REPO_ROOT/AKI-Tray.sh
Icon=$REPO_ROOT/public/obs-tray.svg
Terminal=false
Categories=Utility;Network;
StartupNotify=false
DESKTOP
update-desktop-database "$APPS_DIR" 2>/dev/null || true

# EnvironmentFile instead of one Environment= line per key: .env stays the only place to edit,
# and adding a setting later needs no re-run of this script. The leading '-' makes it optional
# so a missing .env degrades to start.js's own defaults rather than refusing to start.
cat > "$UNIT_PATH" <<UNIT
# Generated by scripts/install-tray.sh — re-run it after moving the repo.
[Unit]
Description=AKI MCP server (gatekeeper + panel + tools, cloudflared ingress)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$REPO_ROOT
EnvironmentFile=-$ENV_FILE
Environment=PATH=$NODE_DIR:/usr/local/bin:/usr/bin:/bin
# A service has no browser to open, whatever .env says.
Environment=MCP_SKIP_BROWSER_OPEN=1
ExecStart=$NODE_BIN ./scripts/start.js
# start.js is foreground by design and tears its own children down on SIGTERM;
# control-group is the cheap guarantee that cloudflared never outlives the unit.
KillMode=control-group
KillSignal=SIGTERM
TimeoutStopSec=20
Restart=on-failure
RestartSec=5
StandardOutput=append:$LOG_DIR/systemd.log
StandardError=append:$LOG_DIR/systemd.err.log

[Install]
WantedBy=default.target
UNIT

systemctl --user daemon-reload

echo "installed  $UNIT_PATH"
echo "           $APPS_DIR/aki-mcp-tray.desktop"
echo "  node      $NODE_BIN"
echo "  env file  $ENV_FILE"
echo "  origin    ${PUBLIC_ORIGIN:-<none>}"
echo "  panel     port $PANEL_PORT (URL with token: ~/.aki/mcpsv/panel-url.txt)"
echo ""
echo "start:   systemctl --user start aki-mcp"
echo "logs:    journalctl --user -u aki-mcp -f"

if ! python3 -c 'import PyQt6.QtWidgets' 2>/dev/null; then
  echo ""
  echo "PyQt6 is missing — the tray needs it:  sudo pacman -S --needed python-pyqt6" >&2
  exit 0
fi

if [[ "${1:-}" != "--no-tray" ]]; then
  echo ""
  echo "starting the tray icon..."
  "$REPO_ROOT/AKI-Tray.sh"
fi
